apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yjx8t83qf-python 
  janus-idp.io/tekton: yjx8t83qf-python
  backstage.io/kubernetes-id: yjx8t83qf-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yjx8t83qf-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml