apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yjx8t83qf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yjx8t83qf-python 
  name: yjx8t83qf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yjx8t83qf-python 
